#!/bin/bash -eu
PROJECT=$(basename "$(git rev-parse --show-toplevel)")
BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref @{upstream} | cut -d/ -f2)

# shellcheck disable=SC2128
SOURCE=$(dirname "$(readlink -f "${BASH_SOURCE}")")

run_conditional() {
    read -r input
    case "${input}" in
        N|n|No|no)
            return 1
        ;;

        *)
            ${1}
            return 0
        ;;
    esac
}

abort() {
    (
        set -x
        git cherry-pick --abort
    )
}

pull() {
    (
        set -x
        cd "${SOURCE}"
        git pull --ff-only
    )
}

push() {
    (
        cd "${SOURCE}"

        if git diff-index --quiet HEAD "${PROJECT}/${BRANCH}"; then
            echo "Nothing to commit"
            exit 0
        fi

        set -x
        cd "${SOURCE}"
        git pull --ff-only
        git commit -s -e -m "${PROJECT}/${BRANCH}: Update commit list" "${PROJECT}/${BRANCH}"
        git push
    )
}

INTERACTIVE="false"
if [ "${1:-}" = "-i" ]; then
    INTERACTIVE="true"

    printf "Refresh the list of processed commits [Y/n]? "
    run_conditional pull || true

    commit() {
        printf "Push the new list of processed commits [Y/n]? "
        run_conditional push || true
    }

    trap commit EXIT
fi

OLD_IFS=${IFS}
IFS='
'
for line in $(git cherry "upstream/${BRANCH}" "upstream/main" -v); do
    IFS=${OLD_IFS}
    # shellcheck disable=SC2086
    set -- ${line}

    [ "$1" = "+" ] || continue

    grep -q "^$2" "${SOURCE}/${PROJECT}/${BRANCH}" && continue

    shift
    if [ "$INTERACTIVE" = "true" ]; then
        while :; do
            echo "$*"
            printf "(A)pply / (S)kip / (F)eature / (I)rrelevant / (D)iffers / (V)iew) / (Q)uit: "
            read -r input
            case "${input}" in
                A|a)
                    if ! git cherry-pick "${1}"; then
                        echo ""
                        printf "Skip this commit for now [Y/n]? "
                        run_conditional abort || exit 1
                    fi
                ;;
                S|s)
                    break
                ;;
                F|f|I|i|D|d)
                    LINE="$1"
                    shift
                    if [ "${input}" = "F" ] || [ "${input}" = "f" ]; then
                        LINE="${LINE}    FEATURE     $*"
                    elif [ "${input}" = "I" ] || [ "${input}" = "i" ]; then
                        LINE="${LINE}    IRRELEVANT  $*"
                    else
                        LINE="${LINE}    DIFFERS     $*"
                    fi
                    echo "${LINE}" >> "${SOURCE}/${PROJECT}/${BRANCH}"
                ;;
                V|v)
                    git show "${1}"
                    continue
                ;;
                Q|q)
                    exit 0
                ;;
                *)
                    echo "Invalid input."
                    continue
                ;;
            esac
            break
        done
    else
        echo "$*"
    fi
done
